import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile, mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {renderMap, validateMap, inspectMap, deliverMap} from '../skills/cx-impact/scripts/render-map.mjs';
const load=async()=>{const module=await import('../skills/cx-impact/assets/comparison-core.js').catch(()=>null);assert.ok(module,'comparison helper must exist');return module.default;};
const flat=JSON.parse(await readFile(new URL('../examples/bicycle-service/map.json',import.meta.url),'utf8'));
function fixture(){const current=structuredClone(flat),target=structuredClone(flat);current.mode='current';target.mode='target';for(const m of [current,target])m.scope={scenario:'Synthetic',start:'Start',end:'End',asOf:'2026-09-08'};return {version:1,mode:'comparison',current,target};}
function matched(){const m=fixture();m.correspondence={stages:m.current.stages.map(s=>({current:[s.id],target:[s.id]})),nodes:m.current.process.nodes.map(n=>({current:[n.id],target:[n.id]})),lanes:m.current.process.lanes.map(l=>({current:[l.id],target:[l.id]}))};return m;}
test('comparison rejects unknown, duplicate and malformed correspondence before rendering',async()=>{const C=await load(),m=fixture(),id=m.current.stages[0].id;for(const stages of [[{current:['missing'],target:[id]}],[{current:[id],target:[id]},{current:[id],target:[id]}],[{current:[],target:[id]}],[{current:[id,id],target:[id]}]]){const bad={...m,correspondence:{stages}};assert.throws(()=>C.validateComparison(bad),/correspondence/);assert.throws(()=>validateMap(bad),/correspondence/);}assert.throws(()=>C.validateComparison({...m,correspondence:{edges:[]}}),/correspondence/);});
test('equal labels and IDs never invent matches; all items survive one-to-many alignment without mutation',async()=>{const C=await load(),m=fixture();const unmatched=C.prepareComparison(m);assert.equal(unmatched.groups.stages.length,m.current.stages.length+m.target.stages.length);assert.ok(unmatched.groups.stages.every(g=>g.match==='unmatched'));const [a,b]=m.current.stages;m.correspondence={stages:[{current:[a.id],target:[a.id,b.id]}]};const before=JSON.stringify(m),r=C.prepareComparison(m),group=r.groups.stages.find(g=>g.match==='explicit');assert.deepEqual(group.current,[a.id]);assert.deepEqual(group.target,[a.id,b.id]);assert.equal(group.span,2);assert.equal(r.stageSlots.filter(s=>s.current).length,m.current.stages.length);assert.equal(r.stageSlots.filter(s=>s.target).length,m.target.stages.length);assert.equal(JSON.stringify(m),before);});
test('source text, status and full branch conditions are content; coordinates and member IDs are not',async()=>{const C=await load(),m=matched();assert.ok(C.prepareComparison(m).groups.nodes.every(g=>g.status==='unchanged'));m.target.process.nodes[0].x=900;assert.equal(C.prepareComparison(m).groups.nodes[0].status,'unchanged');m.target.process.nodes[0].status='hypothesis';assert.ok(C.prepareComparison(m).groups.nodes[0].changes.includes('status'));const s=m.target.sources[0];s.text+=' Revised source.';assert.ok(C.prepareComparison(m).groups.stages.some(g=>g.changes.includes('sources')));const e=m.target.process.edges[0];e.condition='Only after a second explicit approval';assert.ok(C.prepareComparison(m).groups.nodes.some(g=>g.changes.includes('conditions')));});
test('renderer embeds comparison helper, keeps old flat maps and diagnoses paired projected process geometry',async()=>{const m=matched(),html=await renderMap(m);assert.match(html,/CXComparison/);assert.match(html,/compare-toggle/);assert.match(await renderMap(flat),/map-data/);const report=inspectMap(m);assert.equal(report.geometry.comparison.status,'checked');assert.equal(report.geometry.comparison.regions.length,2);assert.equal(report.visual.status,'not_checked');});
test('standalone snapshot includes helper and rebuild is byte-identical',async()=>{const dir=await mkdtemp(join(tmpdir(),'cx-comparison-')),input=join(dir,'map.json'),output=join(dir,'map.html');const {writeFile}=await import('node:fs/promises');await writeFile(input,JSON.stringify(matched()));await deliverMap(input,output);const before=await readFile(output,'utf8');const {execFileSync}=await import('node:child_process');execFileSync(process.execPath,[join(dir,'map.source/rebuild.mjs')]);assert.equal(await readFile(output,'utf8'),before);assert.match(await readFile(join(dir,'map.source/assets/comparison-core.js'),'utf8'),/prepareComparison/);});
test('shared projection aligns process columns and lanes without mutating scenario data',async()=>{const C=await load(),{default:Core}=await import('../skills/cx-impact/assets/map-core.js'),m=matched();m.target.process.nodes[0].title='A longer authored action that needs extra space';const before=JSON.stringify(m),r=C.layoutComparison(m,Core);assert.equal(JSON.stringify(m),before);for(const n of r.regions[0].layout.nodes){const other=r.regions[1].layout.nodes.find(x=>x.id===n.id);assert.equal(n.x,other.x);assert.equal(n.y,other.y);assert.equal(n.h,other.h);}assert.ok(r.regions.every(r=>r.layout.geometry.status==='checked'));});
test('contradictory authored order is diagnosed and never loses a group',async()=>{const C=await load(),m=matched();m.target.stages.reverse();const r=C.prepareComparison(m);assert.ok(r.diagnostics.some(d=>d.code==='ALIGNMENT_ORDER_CONFLICT'));assert.equal(r.groups.stages.length,m.current.stages.length);});
test('public RU/EN synthetic scenarios preserve splits, unmatched stages and changed branch conditions',async()=>{const C=await load();for(const locale of ['ru','en']){const m=JSON.parse(await readFile(new URL(`../skills/cx-impact/examples/scenarios/online-sales.${locale}.json`,import.meta.url),'utf8'));validateMap(m);const r=C.prepareComparison(m);assert.ok(r.groups.stages.some(g=>g.current.length===1&&g.target.length===2));assert.ok(r.groups.stages.some(g=>g.status==='only-in-current'));assert.ok(r.groups.stages.some(g=>g.status==='only-in-target'));assert.ok(r.groups.nodes.some(g=>g.changes.includes('conditions')));assert.equal(inspectMap(m).geometry.status,'checked');}});
test('optional projection does not change ordinary handling of extra authored lane fields',async()=>{const {default:Core}=await import('../skills/cx-impact/assets/map-core.js'),m=fixture().current,before=Core.layoutProcess(m);m.process.lanes[0].height=999;assert.deepEqual(Core.layoutProcess(m),{...before,lanes:before.lanes.map((lane,i)=>i?lane:{...lane,height:999})});});
test('semantic node assignments change independently of coordinates and normalize explicit counterpart IDs',async()=>{
  const C=await load();
  for(const [field,kind]of [['laneId','lanes'],['stageId','stages']]){
    const m=matched(),node=m.target.process.nodes[0],original=node[field];
    const records=kind==='stages'?m.target.stages:m.target.process.lanes;
    node[field]=records.find(x=>x.id!==original).id;
    const changed=C.prepareComparison(m).groups.nodes.find(g=>g.target.includes(node.id));
    assert.equal(changed.status,'changed',`${field} reassignment is content`);
    assert.ok(changed.changes.includes('assignments'));
    const renamed=matched(),record=(kind==='stages'?renamed.target.stages:renamed.target.process.lanes).find(x=>x.id===original),newId=original+'-renamed';
    record.id=newId;for(const n of renamed.target.process.nodes)if(n[field]===original)n[field]=newId;
    const correspondence=renamed.correspondence[kind].find(g=>g.target.includes(original));correspondence.target=correspondence.target.map(id=>id===original?newId:id);
    assert.ok(C.prepareComparison(renamed).groups.nodes.every(g=>g.status==='unchanged'),`${field} corresponding ID rename is not content`);
  }
});
test('retry confirmation requires the same explicit provider approval as direct confirmation in both fixtures',async()=>{
  for(const locale of ['en','ru']){const m=JSON.parse(await readFile(new URL(`../skills/cx-impact/examples/scenarios/online-sales.${locale}.json`,import.meta.url),'utf8')),retry=m.target.process.edges.find(e=>e.id==='e-retry-done'),approved=m.target.process.edges.find(e=>e.id==='e-paid');assert.equal(retry.condition,approved.condition);assert.equal(retry.label,approved.label);}
});
