import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url);
let F;try{F=require('../skills/cx-impact/assets/funnel-core.js');}catch{}
const fixture=async()=>JSON.parse(await readFile(new URL('../skills/cx-impact/examples/funnels/online-sales.en.json',import.meta.url),'utf8'));
test('funnel analysis has honest denominators and conserves authored recovery without mutation',async()=>{
 assert.ok(F,'funnel helper must exist');const data=await fixture(),before=JSON.stringify(data),a=F.analyzeFunnel(data);
 assert.equal(a.stages.at(-1).fromEntry,.042);assert.equal(a.stages.at(-1).fromPrevious,.7);assert.equal(a.repeat.rate,.25);
 assert.equal(a.graph.rootTotal,600);assert.equal(a.graph.sinkTotal,600);assert.equal(a.graph.outcomes.lost,150);assert.equal(a.graph.outcomes.pending,20);assert.equal(a.graph.outcomes.unknown,10);
 assert.equal(JSON.stringify(data),before);const l=F.layoutFunnel(data);assert.deepEqual(l,F.layoutFunnel(data));assert.equal(l.geometry.status,'checked');
 for(const e of l.flows.edges)assert.equal(e.width,e.value*l.flows.scale);
 for(const n of l.flows.nodes){const incoming=l.flows.edges.filter(e=>e.to===n.id),outgoing=l.flows.edges.filter(e=>e.from===n.id);for(const es of [incoming,outgoing])if(es.length)assert.ok(Math.abs(es.reduce((s,e)=>s+e.width,0)-n.h)<1e-8);}
});
test('invalid quantitative contracts identify precise field paths',async()=>{
 assert.ok(F);const checks=[['scope.cohortStart',d=>d.scope.cohortStart='2026-02-30'],['scope.timezone',d=>d.scope.timezone='Fake/Zone'],['scope.asOf',d=>d.scope.asOf='2026-06-08'],['stages[1].count',d=>d.stages[1].count=-1],['stages[1].count',d=>d.stages[1].count=NaN],['stages[1].count',d=>d.stages[1].count=Infinity],['stages[1].count',d=>d.stages[1].count=.5],['stages[1].sourceIds',d=>d.stages[1].sourceIds=[]],['scope.unit',d=>d.scope.unit='orders'],['transitions.scope.rootTotal',d=>d.transitions.scope.rootTotal=601],['transitions.nodes',d=>d.transitions.edges[0].value--],['transitions.edges',d=>d.transitions.edges.push({id:'cycle',from:'paid',to:'checkout',value:1,label:'cycle',sourceIds:['synthetic']})],['repeat.pending',d=>d.repeat.pending=1],['repeat.eligible',d=>{d.scope.asOf='2026-06-20';}],['stages[2].count',d=>{d.stages[1].count=null;d.stages[2].count=11000;}]];
 for(const [path,mutate]of checks){const d=await fixture();mutate(d);assert.throws(()=>F.validateFunnel(d),e=>e.message.includes(path),path);}
});
test('unknown and zero metrics never become positive widths or invented flows',async()=>{assert.ok(F);const d=await fixture();delete d.transitions;delete d.repeat;d.stages[1].count=null;let a=F.analyzeFunnel(d);assert.equal(a.stages[2].fromPrevious,null);assert.equal(a.graph,null);assert.equal(F.layoutFunnel(d).stages[1].w,0);d.stages.forEach(s=>s.count=0);a=F.analyzeFunnel(d);assert.equal(a.stages[0].fromEntry,null);assert.ok(F.layoutFunnel(d).stages.every(s=>s.w===0));});
test('renderer dispatch, check-only and portable snapshots preserve exact source bytes',async()=>{assert.ok(F);const {deliverMap,inspectMap}=await import('../skills/cx-impact/scripts/render-map.mjs');const d=await fixture();assert.equal(inspectMap(d).geometry.status,'checked');const dir=await mkdtemp(join(tmpdir(),'cx-funnel-'));const raw=' \n'+JSON.stringify(d,null,3)+'\n\n',input=join(dir,'input.json'),out=join(dir,'funnel.html');await writeFile(input,raw);execFileSync(process.execPath,['skills/cx-impact/scripts/render-map.mjs','--check',input]);await deliverMap(input,out);const html=await readFile(out,'utf8');assert.ok(html.includes('CXFunnel'));assert.ok(html.includes(Buffer.from(raw).toString('base64')));assert.equal(await readFile(join(dir,'funnel.json'),'utf8'),raw);execFileSync(process.execPath,[join(dir,'funnel.source/rebuild.mjs')]);assert.equal(await readFile(out,'utf8'),html);const manifest=JSON.parse(await readFile(join(dir,'funnel.source/manifest.json')));for(const n of ['comparison-core.js','funnel-core.js','funnel-viewer.js'])assert.ok(manifest.files['assets/'+n]);});
test('layout reports a ribbon passing through a nonincident intermediate node',async()=>{assert.ok(F);const d=await fixture();delete d.repeat;d.stages=d.stages.slice(3);d.stages[1].count=600;d.transitions={scope:{stageId:'checkout',rootTotal:600,denominator:'600 people',description:'Synthetic merge and bypass'},nodes:[['a',300],['b',300],['mid',150],['sink',600]].map(([id,value])=>({id,title:id,value,sourceIds:['synthetic'],...(id==='sink'?{outcome:'progress'}:{})})),edges:[['e1','a','mid',150],['e2','a','sink',150],['e3','b','sink',300],['e4','mid','sink',150]].map(([id,from,to,value])=>({id,from,to,value,label:id,sourceIds:['synthetic']}))};const result=F.layoutFunnel(d);assert.ok(Array.isArray(result.geometry.warnings),'explicit crossing diagnostics required');assert.equal(result.geometry.status,'failed');assert.ok(result.geometry.errors.some(e=>e.code==='RIBBON_NODE_OVERLAP'&&e.node==='mid'&&e.edge==='e2'));});
test('CSV uses raw denominators, RFC quotes, unknown markers and neutralizes authored formulas',async()=>{assert.ok(F);const d=await fixture();d.stages[0].title=' =HYPERLINK("bad")';d.stages[1].definition='@sum(1)\nsecond line';d.stages[1].count=null;const csv=F.funnelCSV(d);assert.match(csv,/"' =HYPERLINK\(""bad""\)"/);assert.match(csv,/"'@sum\(1\)\nsecond line"/);assert.match(csv,/"unknown"/);assert.match(csv,/"0.042"/);assert.match(csv,/"105","420"/);});
test('graph zero flows have no path and repeat immature counts have unknown rate',async()=>{assert.ok(F);const d=await fixture();d.scope.asOf='2026-06-20';d.repeat.eligible=0;d.repeat.purchased=0;d.repeat.pending=420;assert.equal(F.analyzeFunnel(d).repeat.rate,null);const g=d.transitions;g.nodes.push({id:'zero',title:'Explicit zero',value:0,outcome:'unknown',sourceIds:['synthetic']});g.edges.push({id:'zero-edge',from:'checkout',to:'zero',value:0,label:'Explicit zero',sourceIds:['synthetic']});const e=F.layoutFunnel(d).flows.edges.find(e=>e.id==='zero-edge');assert.equal(e.width,0);assert.equal(e.path,null);});
test('source references, unsupported fields and graph metadata cannot silently disappear',async()=>{const cases=[['stages[0].sourceIds',d=>d.stages[0].sourceIds=['missing']],['transitions.scope',d=>delete d.transitions.scope],['transitions.scope.stageId',d=>d.transitions.scope.stageId='missing'],['transitions.edges[0]',d=>d.transitions.edges[0].to='missing'],['transitions.nodes[3].outcome',d=>delete d.transitions.nodes[3].outcome],['scope.timezone',d=>d.scope.timezone='+03:00'],['funnel.revenue',d=>d.revenue=100],['repeat.purchased',d=>d.repeat.purchased=421],['stages[0].count',d=>d.stages[0].count=Number.MAX_SAFE_INTEGER+1]];for(const[path,change]of cases){const d=await fixture();change(d);assert.throws(()=>F.validateFunnel(d),e=>e.message.includes(path),path);}});
test('entry previous metrics are not applicable, distinct from missing measurements',async()=>{const d=await fixture();d.stages[1].count=null;const a=F.analyzeFunnel(d);assert.equal(a.stages[0].previousApplicable,false);assert.equal(a.stages[1].previousApplicable,true);assert.equal(a.stages[0].fromPrevious,null);assert.equal(a.stages[1].fromPrevious,null);const lines=F.funnelCSV(d).split('\r\n');assert.match(lines[1],/"not_applicable"/);assert.match(lines[2],/"unknown"/);});
